# Generated by Django 4.2.3 on 2023-07-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0002_alter_customtoken_key_alter_customtoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAPIKey',
        ),
    ]
