# Generated by Django 4.2.3 on 2023-08-10 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommusic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
