# Generated by Django 4.2.3 on 2023-08-11 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0003_alter_custommusic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
