# Generated by Django 4.2.4 on 2023-08-18 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0005_custommusic_denoised_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommusic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommusic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
