# Generated by Django 4.2.4 on 2023-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0006_custommusic_created_custommusic_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommusic',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
